# Generated by Django 3.1.7 on 2021-04-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
