# Generated by Django 3.1.7 on 2021-04-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_auto_20210403_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='good_rates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rates',
            field=models.IntegerField(default=0),
        ),
    ]
