# Generated by Django 3.1.7 on 2021-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_product_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bad_rates',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='good_rates',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
