# Generated by Django 3.1.7 on 2021-04-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20210403_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rates',
            new_name='bad_rates',
        ),
    ]
