# Generated by Django 3.1.7 on 2021-04-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_auto_20210403_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.product'),
        ),
    ]
