# Generated by Django 3.1.7 on 2021-04-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0006_auto_20210403_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='good_rates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rates',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
