# Generated by Django 3.1.8 on 2021-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('SELLER', 'SELLER'), ('CLIENT', 'CLIENT')], max_length=100)),
            ],
        ),
    ]
