# Generated by Django 3.1.7 on 2021-04-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Accessoirs', 'Accessoirs'), ('Sacs', 'Sacs'), ('Chaussures', 'Chaussures'), ('Robes', 'Robes')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
