# Generated by Django 3.2 on 2021-04-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK')], max_length=50),
        ),
    ]
