# Generated by Django 3.0.5 on 2021-04-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
