# Generated by Django 3.0.5 on 2021-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0005_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
