# Generated by Django 3.0.5 on 2021-04-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0006_seller_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_admin.Seller'),
        ),
    ]
