# Generated by Django 2.2.20 on 2021-04-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0007_product_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
