# Generated by Django 3.0.5 on 2021-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0007_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=-1, max_length=40),
            preserve_default=False,
        ),
    ]
