# Generated by Django 3.0.5 on 2021-04-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0008_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
