# Generated by Django 3.0.5 on 2021-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0009_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
