# Generated by Django 3.0.5 on 2021-04-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0010_auto_20210416_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='nbElementProd',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='profitProd',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='resteProd',
        ),
    ]
